<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.17763.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <Description>MacOS Dock for Windows </Description>
    <PackageIcon>icon.png</PackageIcon>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <Copyright>Copyright (C) 2026 omerdev</Copyright>
    <Version>6.0.0</Version>
    <AssemblyVersion>6.0.0</AssemblyVersion>
    <FileVersion>6.0.0</FileVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="icon.ico" />
  </ItemGroup>


  <ItemGroup>
    <None Include="folder.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="folder.png" />
    <EmbeddedResource Include="icon.png" />
  </ItemGroup>

  <Target Name="CreateInstallerAlias" AfterTargets="Build">
    <Copy SourceFiles="$(TargetDir)$(TargetName).exe" DestinationFiles="$(TargetDir)Installer.exe" SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(TargetDir)$(TargetName).runtimeconfig.json" DestinationFiles="$(TargetDir)Installer.runtimeconfig.json" SkipUnchangedFiles="true" Condition="Exists('$(TargetDir)$(TargetName).runtimeconfig.json')" />
  </Target>

</Project>
